# Test your endpoints

GET https://mdpan.dev
Accept: application/json
###
GET https://www.mdpan.dev
Accept: application/json

###
GET 34.28.97.199:443
Accept: application/json
###
GET http://www.mdpan.dev/
Accept: application/json

###
GET http://0.0.0.0:80/resources/MarioDanielPanuco%20-%20Resume.pdf
Accept: application/pdf

###

GET http://0.0.0.0:80/eigen/
Accept: application/json

###
